[package]
name = "bls_signatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ark-bls12-381 = "0.4"
ark-ec = "0.4"
rand = "0.8"
ark-std = "0.4"
blake2 = "0.10"
ark-ff = "0.4"